name: Release

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Release request dispatch
        run: |
          curl -X POST \
              -H "Authorization: Bearer ${{ secrets.JAOWEB_GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.everest-preview+json" \
              https://api.github.com/repos/jaoafa/jaoweb-docs/actions/workflows/release.yml/dispatches --data '{"ref": "main"}'
